steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - europe-west1-docker.pkg.dev/${PROJECT_ID}/classi-fruits-repo/classi-fruits:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-west1-docker.pkg.dev/${PROJECT_ID}/classi-fruits-repo/classi-fruits:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=europe-west1-docker.pkg.dev/${PROJECT_ID}/classi-fruits-repo/classi-fruits:latest
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --memory=2Gi
      - --cpu=2
      - --timeout=300

images:
  - europe-west1-docker.pkg.dev/${PROJECT_ID}/classi-fruits-repo/classi-fruits:latest

substitutions:
  _SERVICE_NAME: classi-fruits
  _REGION: europe-west1
